model:
    arch: frrnA
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 256 # 512
    img_cols: 512 # 1024
    path: /home/jovyan/Cityscapes
training:
    loss: 
        name: bootstrapped_cross_entropy
        K: 32768
    n_workers: 10
    train_iters: 45000
    batch_size: 3
    val_interval: 2500
    print_interval: 25
    optimizer:
        name: adam
        lr: 1.0e-3
    lr_schedule:
        name: multi_step
        gamma: 0.1
        milestones: [35000, ]
    augmentations:
        translate: [64, 128]
        gamma: 0.75
    resume: null



