apiVersion: batch/v1
kind: Job
metadata:
  name: exp-name
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/zxy/mydocker:latest
        command: ["bash", "-c"]
        args: ["bash {repo_path}/prepare_data.sh cifar100 && bash {repo_path}/qr.sh a75_mag_top_loc_st"]
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4
            memory: "8Gi"
          requests:
            cpu: 4
            memory: "8Gi"
        volumeMounts:
        - mountPath: /dataset/
          name: zxy-volume-ceph-dataset
        - mountPath: /dev/shm
          name: dshm

      restartPolicy: Never
      volumes:
        - name: zxy-volume-ceph-dataset
          persistentVolumeClaim:
            claimName: zxy-volume-ceph-dataset
        - name: dshm
          emptyDir:
            medium: Memory

      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
               - key: nvidia.com/gpu.memory
                 operator: In
                 values: 
                  - "11264"
                  - "12288"
                  - "15109"
                  - "15360"
                  - "11177"
                  - "8192"
                  - "11178"
                  - "8127"
                  - "11018"
                  - "8118"
                  - "11441"
                  - "9856"
                  - "12196"
                  - "11019"
                  - "8119"

                  # for unet, frrnb and densenet, use gpu memory >= 11k
                  # others will do fine with gpu memory >= 8k 